basketballleagueV1/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path
from django.views.generic import RedirectView
from django.conf.urls import include


urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^teams/', include('teams.urls')),
    re_path(r'^coaches/', include('coachesv2.urls')),
    re_path(r'^players/', include('players.urls')),
    re_path(r'^fixtures/', include('fixtures.urls')),
    re_path(r'^stats/', include('sitestats.urls')),
    re_path(r'^$', RedirectView.as_view(url='fixtures/scorecard'), name='index')
]

urlpatterns += staticfiles_urlpatterns()

players/urls.py
from django.urls import re_path
from . import views

app_name = 'players'

urlpatterns = [
    re_path(r'^(?P<player_id>[\w-]+)/$', views.player_view, name="player"),
    re_path(r'^filter/team=(?P<team_code>[\w-]+)(.*\&?filter=(?P<percentile>([0-9]+)).*)?/$', views.filter_view, name="filter"),
]

teams/urls.py
from django.urls import re_path
from . import views

app_name = 'teams'

urlpatterns = [
    re_path(r'^$', views.team_list_view, name="team_list"),
    re_path(r'^(?P<code>[\w-]+)/$', views.team_view, name="team_details"),
]

teams/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(
        verbose_name='Team Name',
        max_length=100,
    )

    short_code = models.CharField(
        verbose_name='Team Code',
        max_length=10,
        null=True,
    )

    coach = models.OneToOneField(
        'coachesv2.Coach', related_name='team',
        verbose_name='Coach',
        on_delete=models.CASCADE,
        null=True, blank=True
    )

    def __str__(self):
        return self.name

teams/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseForbidden
from accounts.models import User
from fixtures.models import Game
from .models import Team
from django.shortcuts import get_object_or_404, render


@login_required
def team_list_view(request):
    user = User.objects.get(id=request.user.id)
    if user.user_type == User.Admin:
        teams = Team.objects.all()
        return render(request, 'teams/team_list.html', {'teams': teams})
    else:
        return HttpResponseForbidden()


@login_required
def team_view(request, code):
    user = User.objects.get(id=request.user.id)
    if user.user_type != User.Player:
        team = get_object_or_404(Team, short_code=code)
        players = team.player.all()
        games_played = Game.objects.filter(Q(home_team=team) | Q(away_team=team))
        details = {'team': team, 'players': players, 'avg': calculate_avg_score(team, games_played)}
        return render(request, 'teams/team.html', details)
    else:
        return HttpResponseForbidden()


def calculate_avg_score(team, games_played):
    """
    This method will calculate the average score for a team
    @param games_played:
    @param team: Team
    @return: float average
    """

    total_points = 0
    total_games = 0
    average_score = 0
    for game in games_played:
        if game.home_team == team:
            total_points += game.home_team_score
        else:
            total_points += game.away_team_score
        total_games += 1

    if total_games > 0:
        average_score = total_points/total_games
    return average_score

teams/templates/teams/team.html
{% extends 'base.html' %}

{% block content%}

    <div>
        <h1>{{ team.name }} ({{ team.short_code }})</h1>

        <h3>Average score: {{ avg }}</h3>
        <h2>Players</h2>

        <ol>
            {% for player in players %}
                <li>

                    <div>
                        <h3><a href="{% url 'players:player' player_id=player.id %}">{{ player }}</a></h3>
                        <p>height: {{ player.height }}cm</p>
                        <p>weight: {{ player.weight }}kg</p>
                    </div>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}

teams/templates/teams/team_list.html
{% extends 'base.html' %}

{% block content%}
    <div>
        <h2>Registered Teams</h2>
        <ol>
            {% for team in teams %}
                <li>
                    <div>
                        <h3><a href="{% url 'teams:team_details' code=team.short_code %}">{{ team.name }} ({{ team.short_code}})</a></h3>
                    </div>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}